### ISSUE TITLE
[React][Accordion] proxyState is not iterable

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/ark#1522]
### Description

I am trying to implement a accordion component and I'm getting this error: 
![Screenshot from 2023-10-09 16-28-02](https://github.com/chakra-ui/ark/assets/62773200/a896b170-d034-4eab-ad2e-a5c18742a7bc)

TypeError: proxyState is not iterable
    at snapshot (http://localhost:6006/vendors-node_modules_ark-ui_react_accordion_index_mjs-node_modules_babel_runtime_helpers_esm_-2202d7.iframe.bundle.js:3711:51)
    at http://localhost:6006/vendors-node_modules_ark-ui_react_accordion_index_mjs-node_modules_babel_runtime_helpers_esm_-2202d7.iframe.bundle.js:3393:83
    at mountSyncExternalStore (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_defineProperty_js-node_modules_babel_runtime_h-8e0403.iframe.bundle.js:42940:20)
    at Object.useSyncExternalStore (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_defineProperty_js-node_modules_babel_runtime_h-8e0403.iframe.bundle.js:43868:14)
    at useSyncExternalStore (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_defineProperty_js-node_modules_babel_runtime_h-8e0403.iframe.bundle.js:58770:21)
    at useSnapshot (http://localhost:6006/vendors-node_modules_ark-ui_react_accordion_index_mjs-node_modules_babel_runtime_helpers_esm_-2202d7.iframe.bundle.js:3383:83)
    at useMachine (http://localhost:6006/vendors-node_modules_ark-ui_react_accordion_index_mjs-node_modules_babel_runtime_helpers_esm_-2202d7.iframe.bundle.js:3451:17)
    at useAccordion (http://localhost:6006/vendors-node_modules_ark-ui_react_accordion_index_mjs-node_modules_babel_runtime_helpers_esm_-2202d7.iframe.bundle.js:355:82)
    at http://localhost:6006/vendors-node_modules_ark-ui_react_accordion_index_mjs-node_modules_babel_runtime_helpers_esm_-2202d7.iframe.bundle.js:266:85
    at renderWithHooks (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_defineProperty_js-node_modules_babel_runtime_h-8e0403.iframe.bundle.js:42446:18)

### Link to Reproduction

https://github.com/FilipePfluck/PlucoUI/tree/main/src/components/primitives/disclosure/Accordion

### Steps to reproduce

clone the repository
run the storybook
check the accordion story

### Ark UI Version

0.15

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. 

This is most likely related to having two different version of Ark UI or Zag.js in your project. Kindly resolve to a single version to fix the issue.
