### ISSUE TITLE
Upgrading to ark 1.0

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/ark#1680]
### Description

I am upgrading to ark 1.0 and some components have broken. 
Accordion, Toggle Group, Radio Group, Dialog crash. The Tab component doesn't crash but it doesn't work anymore. They are mentioned in the changelog, but I can't see any guide on how to upgrade the version on the docs. 

Here's the error I get in Toggle group: 
TypeError: Cannot read properties of undefined (reading '__base__')
    at StyledComponent (http://localhost:6006/main.iframe.bundle.js:1462:48)
    at renderWithHooks (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:38293:18)
    at updateForwardRef (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:42278:20)
    at beginWork$1 (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:44969:16)
    at beginWork (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:53285:14)
    at performUnitOfWork (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:52136:12)
    at workLoopSync (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:51852:5)
    at renderRootSync (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:51807:7)
    at recoverFromConcurrentError (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:51042:20)
    at performConcurrentWorkOnRoot (http://localhost:6006/vendors-node_modules_pnpm_ark-ui_react_1_0_1__internationalized_date_3_5_0_react-dom_18_2_0_r-fdca06.iframe.bundle.js:50948:22)
    
    I get a similar error in the other components, except for dialog, in which I get this error: 
    
    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `DialogContent`.

I've spend some time trying to figure this out but I don't know how to solve this error

### Link to Reproduction (or Detailed Explanation)

https://github.com/FilipePfluck/PlucoUI

### Steps to Reproduce

clone the repo
run the storybook server
check out the components mentioned

### Ark UI Version

1.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
@FilipePfluck 

To achieve a consistent and more intuitive API we had to rename some parts. When you open the files in your project you can clearly spot the issues:

<img width="459" alt="Bildschirmfoto 2023-11-10 um 22 49 53" src="https://github.com/chakra-ui/ark/assets/1846056/435909d3-605a-420e-b298-d04044738d95">


Please refer to the [docs](https://ark-ui.com)  for the components mentioned to learn more.

**Comment by FilipePfluck** [comment]
thanks for the fast response @cschroeter for some reason my vscode wasn't indicating errors

**Comment by Omikorin** [comment]
Look at methods such as `onValueChange` or 
`onOpenChange`, you will usually need them more often instead of `onChange`
