### ISSUE TITLE
No such file node_modules dependencies @zag-js/date-picker

### ISSUE THREAD

**Issue by bojkomatias** [chakra-ui/ark#2530]
### Description

I just started a Solid Start app, and went to use some components from Ark UI, some inputs, menus, etc. Simple stuff. 

I'm having the follwing error message, dev server starts but takes about 5 or so seconds, and running on build directly crashed the program.

```
$ vinxi dev
vinxi v0.3.11
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

5:07:02 PM [vite] Failed to load source map for /Users/matias/ts-web-app-template/node_modules/@ark-ui/anatomy/node_modules/@zag-js/number-input/node_modules/@internationalized/number/dist/NumberFormatter.mjs.
Error: An error occurred while trying to read the map file at NumberFormatter.mjs.map
Error: ENOENT: no such file or directory, open '/Users/matias/ts-web-app-template/node_modules/@ark-ui/anatomy/node_modules/@zag-js/number-input/node_modules/@internationalized/number/dist/NumberFormatter.mjs.map'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1251:14)
    at async extractSourcemapFromFile (file:///Users/matias/ts-web-app-template/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:16733:10)
    at async loadAndTransform (file:///Users/matias/ts-web-app-template/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:55018:35)
5:07:02 PM [vite] Failed to load source map for /Users/matias/ts-web-app-template/node_modules/@ark-ui/anatomy/node_modules/@zag-js/number-input/node_modules/@internationalized/number/dist/NumberParser.mjs.
Error: An error occurred while trying to read the map file at NumberParser.mjs.map
Error: ENOENT: no such file or directory, open '/Users/matias/ts-web-app-template/node_modules/@ark-ui/anatomy/node_modules/@zag-js/number-input/node_modules/@internationalized/number/dist/NumberParser.mjs.map'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1251:14)
    at async extractSourcemapFromFile (file:///Users/matias/ts-web-app-template/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:16733:10)
    at async loadAndTransform (file:///Users/matias/ts-web-app-template/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:55018:35)
```

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/github-aygfsy?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce

1. Run pnpm dev to see the issue.

### Ark UI Version

3.2.1

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

All

**Comment by cschroeter** [comment]
@bojkomatias 

Thanks for taking your time to report this issue. This was an issue in one of the dependencies in Zag and has been resolved. 
As soon as they ship a new version this error will be resolved.

For reference: https://github.com/adobe/react-spectrum/issues/6355
