### ISSUE TITLE
Error: The requested module 'solid-js/web' does not provide an export named 'memo'

### ISSUE THREAD

**Issue by amirhhashemi** [chakra-ui/ark#723]
I'm using Solid with Astro in my project. When I use `ark` in a component that runs on the server (doesn't have `client:only` directive) I get this error:
```
/node_modules/.pnpm/@ark-ui+solid@0.0.0-rc-20230403193437_solid-js@1.6.16/node_modules/@ark-ui/solid/dist/environment/environment.mjs:1
import { createComponent, memo, use, template } from 'solid-js/web';
                          ^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'memo'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async nodeImport (/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:54039:21)
    at async eval (/src/pages/_Editor.tsx:24:31)
    at async instantiateModule (/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:53996:9)
```

I'm using your default Accordion example:
```ts
// Accordion.tsx
import {
  Accordion,
  AccordionTrigger,
  AccordionItem,
  AccordionContent,
} from '@ark-ui/solid'

export const CustomAccordion = () => {
  return (
    <Accordion>
      <AccordionItem value="panel-1">
        <AccordionTrigger>
          <button>Panel 1 trigger</button>
        </AccordionTrigger>
        <AccordionContent>Panel 1 content</AccordionContent>
      </AccordionItem>
    
      <AccordionItem value="panel-2">
        <AccordionTrigger>
          <button>Panel 2 trigger</button>
        </AccordionTrigger>
        <AccordionContent>Panel 2 content</AccordionContent>
      </AccordionItem>
    </Accordion>
  )
}
```
```astro
// /pages/index.astro
---
  import { CustomAccordion } from "./Accordion"
---
<CustomAccordion client:load />
```

ark version: `0.0.0-rc-20230403193437` (the latest rc version)

**Comment by ahhshm** [comment]
Well, solid doesn't have `memo` it only has `createMemo`

**Comment by cschroeter** [comment]
Should be resolved in the latest version.

**Comment by lamualfa** [comment]
@cschroeter the new version is not published yet.

**Temporary solution:**

```bash
# NPM
npm i "https://gitpkg.now.sh/chakra-ui/ark/packages/solid?main"

# PNPM
pnpm add "https://gitpkg.now.sh/chakra-ui/ark/packages/solid?main"

# Yarn
yarn add "https://gitpkg.now.sh/chakra-ui/ark/packages/solid?main"
```

**Comment by cschroeter** [comment]
Can you try with `@ark-ui/solid@0.1.0` ?
